
networks:
  openfga:
services:
  postgres:
    image: postgres:16
    container_name: app_db
    networks:
      - openfga
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - "./postgres_config/postgres.conf:/etc/postgresql/postgresql.conf"
    command: "postgres -c config_file=/etc/postgresql/postgresql.conf"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  python:
    build: ./db_init
    container_name: db_init
    networks:
      - openfga
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - "./db_init:/app"
    command: ["python", "/app/create_table.py"]