name: Python Scraper Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.8'  
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Woolworths Scraper
      env:
        # Load environment variables from .env.mongo
        $(cat .env.mongo | xargs)
      run: |
        python DiscountMate_new/Scrapping/Australia_GroceriesScraper/scraper_woolworths.py

    - name: Upload MongoDB logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: mongodb_logs.txt
