name: Automate Woolworths Scraper

on:
  schedule:
    # Runs every Wednesday at 3:00 AM UTC
    - cron: '0 3 * * 3'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Set up ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+' | head -1)
          echo "Detected Chrome major version: $CHROME_VERSION"
          # Try to get the matching ChromeDriver version for the detected major Chrome version
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION || echo "latest")
          if [ "$CHROMEDRIVER_VERSION" == "latest" ]; then
            echo "Could not find specific ChromeDriver version for $CHROME_VERSION. Downloading the latest ChromeDriver."
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi
          echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
          curl -sS -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          sudo unzip -q /tmp/chromedriver.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Scrapping/Australia_GroceriesScraper/requirements.txt

      - name: Set up environment variables
        run: |
          echo "MONGO_USERNAME=discountmate" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=discountmate1" >> $GITHUB_ENV

      - name: Run Woolworths scraper script
        run: |
          python Scrapping/Australia_GroceriesScraper/scraper_woolworths.py
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

      - name: Upload MongoDB logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: mongodb_logs.txt
