name: Automate Woolworths Scraper

on:
  schedule:
    # Runs every Wednesday at 3:00 AM UTC
    - cron: '0 3 * * 3'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to the latest version
        with:
          python-version: '3.11.8'  # Using Python version 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Scrapping/Australia_GroceriesScraper/requirements.txt
          pip install selenium webdriver-manager beautifulsoup4

      - name: Install Chrome Driver
        uses: nanasess/setup-chromedriver@v3
        with:
          chromedriver-version: 'latest'

      - name: Run Woolworths scraper script
        run: |
          python Scrapping/Australia_GroceriesScraper/scraper_woolworths.py

      - name: Archive Results
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: Scrapping/Australia_GroceriesScraper/Woolworths.csv
