name: Automate Woolworths Scraper

on:
  schedule:
    # Runs every Wednesday at 3:00 AM UTC
    - cron: '0 3 * * 3'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to the latest version
        with:
          python-version: '3.11.8'  # Updated to use Python version 3.11.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Scrapping/Australia_GroceriesScraper/requirements.txt  # Adjust the path if needed

      - name: Run Woolworths scraper script
        run: |
          python Scrapping/Australia_GroceriesScraper/scraper_woolworths.py
